name: Publish Npm
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  # Lint:
    # Lint任务
  UnitTest:
    # 单元测试任务
    - name: Run Test
      run: pnpm run test:run
